version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: osint_4d_db
    restart: always  # 재부팅해도 자동 실행
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: osint_4d
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgis_data:
