const { app, BrowserWindow, dialog, Menu, Tray, shell, ipcMain } = require("electron");
const { spawn, execSync } = require("child_process");
const path = require("path");
const http = require("http");
const fs = require("fs");

// --- Configuration ---
const PORT = 8002;
const SERVER_URL = `http://127.0.0.1:${PORT}`;
const HEALTH_URL = `${SERVER_URL}/health`;
const MAX_STARTUP_WAIT_MS = 30_000;

let mainWindow = null;
let splashWindow = null;
let setupWindow = null;
let backendProcess = null;
let tray = null;
let isQuitting = false;

// --- Path resolution ---
function getResourcePath() {
  if (app.isPackaged) {
    return path.join(process.resourcesPath);
  }
  return path.join(__dirname, "..");
}

function getEnvFilePath() {
  // Packaged: write to userData (persistent across updates)
  // Dev: write to project root
  if (app.isPackaged) {
    return path.join(app.getPath("userData"), ".env");
  }
  return path.join(__dirname, "..", ".env");
}

// --- Check if first run (no .env or no AIS_API_KEY) ---
function needsSetup() {
  const envPath = getEnvFilePath();
  // Also check project root .env for dev mode
  const altEnvPath = path.join(getResourcePath(), ".env");

  for (const p of [envPath, altEnvPath]) {
    if (fs.existsSync(p)) {
      const content = fs.readFileSync(p, "utf-8");
      if (content.includes("AIS_API_KEY=") && !content.includes("AIS_API_KEY=\n") && !content.includes("AIS_API_KEY=''")) {
        // Check the value is not empty
        const match = content.match(/AIS_API_KEY=(.+)/);
        if (match && match[1].trim().length > 0) {
          return false;
        }
      }
    }
  }
  return true;
}

// --- Write .env file ---
function writeEnvFile(config) {
  const envPath = getEnvFilePath();
  const lines = [];

  // Read existing .env if present, preserving unknown keys
  if (fs.existsSync(envPath)) {
    const existing = fs.readFileSync(envPath, "utf-8").split("\n");
    const configKeys = new Set(Object.keys(config));
    for (const line of existing) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) {
        lines.push(line);
        continue;
      }
      const eqIdx = trimmed.indexOf("=");
      if (eqIdx > 0) {
        const key = trimmed.slice(0, eqIdx);
        if (!configKeys.has(key)) {
          lines.push(line); // Keep keys not in new config
        }
      }
    }
  } else {
    lines.push("# 4DWAR Configuration");
    lines.push("# Generated by setup wizard");
    lines.push("");
  }

  // Add new config values
  for (const [key, value] of Object.entries(config)) {
    if (value) {
      lines.push(`${key}=${value}`);
    }
  }

  // Ensure directory exists
  const dir = path.dirname(envPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(envPath, lines.join("\n") + "\n");
  console.log(`[4DWAR] Config saved to: ${envPath}`);
}

// --- Find system Python ---
function findPython() {
  const candidates = ["python3", "python"];
  for (const cmd of candidates) {
    try {
      const version = execSync(`${cmd} --version 2>&1`, {
        encoding: "utf-8",
        timeout: 5000,
      }).trim();
      const match = version.match(/Python (\d+)\.(\d+)/);
      if (match && parseInt(match[1]) >= 3 && parseInt(match[2]) >= 10) {
        return cmd;
      }
    } catch {
      // Not found, try next
    }
  }
  return null;
}

// --- Load .env file into env object ---
function loadEnvFile(basePath) {
  const env = { ...process.env, PORT: String(PORT), PYTHONUNBUFFERED: "1" };

  const envPaths = [
    getEnvFilePath(),
    path.join(basePath, ".env"),
  ];

  for (const envFile of envPaths) {
    if (fs.existsSync(envFile)) {
      const lines = fs.readFileSync(envFile, "utf-8").split("\n");
      for (const line of lines) {
        const trimmed = line.trim();
        if (trimmed && !trimmed.startsWith("#")) {
          const eqIdx = trimmed.indexOf("=");
          if (eqIdx > 0) {
            env[trimmed.slice(0, eqIdx)] = trimmed.slice(eqIdx + 1);
          }
        }
      }
      console.log(`[4DWAR] Loaded env from: ${envFile}`);
      break;
    }
  }

  return env;
}

// --- Health check ---
function waitForServer() {
  return new Promise((resolve, reject) => {
    const startTime = Date.now();

    function check() {
      if (Date.now() - startTime > MAX_STARTUP_WAIT_MS) {
        return reject(new Error("Server startup timed out"));
      }

      http
        .get(HEALTH_URL, (res) => {
          if (res.statusCode === 200) {
            resolve();
          } else {
            setTimeout(check, 500);
          }
        })
        .on("error", () => {
          setTimeout(check, 500);
        });
    }

    check();
  });
}

// --- Setup window ---
function createSetupWindow() {
  return new Promise((resolve) => {
    setupWindow = new BrowserWindow({
      width: 520,
      height: 580,
      frame: false,
      resizable: false,
      backgroundColor: "#0a0a0a",
      webPreferences: {
        preload: path.join(__dirname, "preload-setup.js"),
        nodeIntegration: false,
        contextIsolation: true,
      },
    });

    setupWindow.loadFile(path.join(__dirname, "setup.html"));
    setupWindow.center();

    // Handle save from setup window
    ipcMain.once("setup-save", (_event, config) => {
      if (config && Object.keys(config).length > 0) {
        writeEnvFile(config);
      }
      setupWindow.close();
      setupWindow = null;
      resolve();
    });

    // Handle external URL opens
    ipcMain.on("setup-open-url", (_event, url) => {
      shell.openExternal(url);
    });

    // Handle window close (treat as skip)
    setupWindow.on("closed", () => {
      setupWindow = null;
      resolve();
    });
  });
}

// --- Splash screen ---
function createSplashWindow() {
  splashWindow = new BrowserWindow({
    width: 420,
    height: 300,
    frame: false,
    transparent: true,
    alwaysOnTop: true,
    resizable: false,
    webPreferences: { nodeIntegration: false, contextIsolation: true },
  });

  splashWindow.loadFile(path.join(__dirname, "splash.html"));
  splashWindow.center();
}

// --- Main window ---
function createMainWindow() {
  mainWindow = new BrowserWindow({
    width: 1600,
    height: 1000,
    minWidth: 1024,
    minHeight: 700,
    title: "4DWAR — Maritime OSINT Sentry",
    backgroundColor: "#0a0a0a",
    show: false,
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
      nodeIntegration: false,
      contextIsolation: true,
    },
  });

  mainWindow.loadURL(SERVER_URL);

  mainWindow.once("ready-to-show", () => {
    if (splashWindow) {
      splashWindow.close();
      splashWindow = null;
    }
    mainWindow.show();
    mainWindow.focus();
  });

  mainWindow.on("close", (e) => {
    if (!isQuitting) {
      e.preventDefault();
      mainWindow.hide();
    }
  });

  mainWindow.on("closed", () => {
    mainWindow = null;
  });

  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    shell.openExternal(url);
    return { action: "deny" };
  });
}

// --- Start backend ---
function startBackend() {
  const pythonCmd = findPython();
  if (!pythonCmd) {
    dialog.showErrorBox(
      "4DWAR — Python Not Found",
      "Python 3.10+ is required to run 4DWAR.\n\n" +
        "Install from https://python.org\n" +
        "Then run: pip install -r requirements-lite.txt"
    );
    app.quit();
    return null;
  }

  // Determine working directory for backend
  let backendCwd;
  if (app.isPackaged) {
    backendCwd = path.join(process.resourcesPath, "app");
  } else {
    backendCwd = path.join(__dirname, "..");
  }

  const env = loadEnvFile(backendCwd);

  console.log(`[4DWAR] Starting: ${pythonCmd} -m uvicorn (cwd: ${backendCwd})`);
  const proc = spawn(
    pythonCmd,
    ["-m", "uvicorn", "backend.main:app", "--host", "127.0.0.1", "--port", String(PORT)],
    { cwd: backendCwd, env, stdio: ["ignore", "pipe", "pipe"] }
  );

  proc.stdout.on("data", (data) => {
    process.stdout.write(`[backend] ${data}`);
  });

  proc.stderr.on("data", (data) => {
    process.stderr.write(`[backend] ${data}`);
  });

  proc.on("exit", (code) => {
    console.log(`[4DWAR] Backend exited with code ${code}`);
    if (!isQuitting) {
      dialog.showErrorBox(
        "4DWAR — Backend Stopped",
        `The backend server exited unexpectedly (code: ${code}).\n\nCheck logs for details.`
      );
      app.quit();
    }
  });

  return proc;
}

function stopBackend() {
  if (backendProcess) {
    console.log("[4DWAR] Stopping backend...");
    backendProcess.kill("SIGTERM");

    const proc = backendProcess;
    setTimeout(() => {
      try {
        proc.kill("SIGKILL");
      } catch {
        // Already dead
      }
    }, 5000);

    backendProcess = null;
  }
}

// --- System tray ---
function createTray() {
  tray = new Tray(path.join(__dirname, "icons", "tray.png"));

  const contextMenu = Menu.buildFromTemplate([
    {
      label: "Open 4DWAR",
      click: () => {
        if (mainWindow) { mainWindow.show(); mainWindow.focus(); }
      },
    },
    { type: "separator" },
    {
      label: "Settings",
      click: async () => {
        await createSetupWindow();
        // Restart backend to pick up new config
        if (backendProcess) {
          stopBackend();
          backendProcess = startBackend();
        }
      },
    },
    {
      label: "Open in Browser",
      click: () => shell.openExternal(SERVER_URL),
    },
    { type: "separator" },
    {
      label: "Quit",
      click: () => { isQuitting = true; app.quit(); },
    },
  ]);

  tray.setToolTip("4DWAR — Maritime OSINT Sentry");
  tray.setContextMenu(contextMenu);
  tray.on("click", () => {
    if (mainWindow) { mainWindow.show(); mainWindow.focus(); }
  });
}

// --- App lifecycle ---
app.whenReady().then(async () => {
  // Step 1: Show setup if first run
  if (needsSetup()) {
    await createSetupWindow();
  }

  // Step 2: Splash + start backend
  createSplashWindow();

  backendProcess = startBackend();
  if (!backendProcess) return;

  try {
    await waitForServer();
  } catch (err) {
    if (splashWindow) splashWindow.close();
    dialog.showErrorBox(
      "4DWAR — Startup Failed",
      `Could not start the backend server.\n\n${err.message}`
    );
    stopBackend();
    app.quit();
    return;
  }

  // Step 3: Main window
  createMainWindow();

  const trayIcon = path.join(__dirname, "icons", "tray.png");
  if (fs.existsSync(trayIcon)) {
    createTray();
  }
});

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    isQuitting = true;
    app.quit();
  }
});

app.on("activate", () => {
  if (mainWindow) { mainWindow.show(); }
});

app.on("before-quit", () => {
  isQuitting = true;
  stopBackend();
});
